main: com.kale_ko.evercraft.spigot.SpigotMain

name: EverCraft
version: ${plugin_version}
description: A custom plugin to run on EverCraft
author: Kale Ko
website: https://github.com/EverCraft-MC/EverCraft

api-version: "1.18"
load: POSTWORLD

depend: [LuckPerms]
