main: com.kale_ko.kalesutilities.spigot.SpigotPlugin

name: KalesUtilities
version: ${plugin_version}
description: A custom plugin to run on KalesMC
author: Kale Ko
website: https://github.com/Kale-Ko/Kales-Utilities-V2

api-version: "1.18"
load: POSTWORLD

depend: [LuckPerms]
