main: io.github.evercraftmc.core.impl.paper.ECPaperPluginLoader

name: "EverCraft"
version: "${version}"
description: "The EverCraft plugin"

authors: [ "Kale-Ko" ]
website: "https://github.com/EverCraftMC/EverCraft"

api-version: "1.21"
load: STARTUP