main: io.github.evercraftmc.core.impl.spigot.ECSpigotPluginLoader

name: EverCraft-Core
description: EverCraft-Core
version: ${version}

author: Kale Ko
website: https://github.com/EverCraftMC

api-version: 1.19
load: STARTUP
